version: '3.8'
services:
  postfix:
    build: .
    ports:
      - 25:25
      - 587:587
    volumes:
      - ./conf/sasl_passwd.map:/overrides/sasl_passwd.map

    tty: true
    environment:
       DOMAIN: ${DOMAIN}
       RELAYNETS: ${RELAYNETS}
       HOSTNAME: ${HOSTNAME}
       RELAYHOST: ${RELAYHOST}
       MESSAGE_SIZE_LIMIT: ${MESSAGE_SIZE_LIMIT}
       TLS: ${TLS}
       SASL_AUTH: ${SASL_AUTH}
